training_args:
  output_dir: "models/slue_sqa5-flan-t5-base-qformer"
  run_name: "slue_sqa5-flan-t5-base-qformer"
  max_steps: 250000
  per_device_train_batch_size: 36
  per_device_eval_batch_size: 8
  evaluation_strategy: "steps"
  eval_steps: 1000
  save_strategy: "steps"
  save_steps: 1000
  save_total_limit: 4
  load_best_model_at_end: true
  learning_rate: 0.0001
  warmup_steps: 5000
  gradient_accumulation_steps: 4
  dataloader_num_workers: 0
  dataloader_drop_last: false
  logging_steps: 50
  report_to:
    - wandb
  save_safetensors: true
  metric_for_best_model: "Hits@20"
  greater_is_better: true
