defaults:
  - training: qg_base
  - _self_

task: qg

model:
  model_name_or_path: "google/flan-t5-base"
  final_model_dir: "models/qg/flan-t5-base"
  special_token: 32000
  model_path: null

data:
  dataset_path: ${oc.env:SLUE_SQA5_DATASET_PATH,${hydra:runtime.cwd}/outputs/slue_wavtok/csv}
  code_path: ${oc.env:SLUE_SQA5_CODE_PATH,${hydra:runtime.cwd}/outputs/slue_wavtok/precomputed}
  split: "train"
  max_length: 512
  discrete_code_num: 512
  lookup_file_name: ${oc.env:SLUE_SQA5_TOKEN_LOOKUP_PATH,${hydra:runtime.cwd}/outputs/slue_wavtok/flan-t5-base-unused_tokens.txt}

wandb:
  project: "Audio-QG"
  description: null
