defaults:
  - /data@data: slue_sqa5_wavtok
  - /model@model: flan_t5_base
  - /training@training: run_base
  - /logging@logging: wandb
  - _self_

task: retrieval

run:
  max_length: 512
  id_max_length: 128
  top_k: 10
  num_return_sequences: 10
  generation_max_length: 20
  run_notes: "fine-tune on flan-t5 with 500 cluster discrete units on layer 22"
  log_eval_artifacts: false
  log_eval_raw_predictions: false
